name: Install Nginx and echo Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Nginx
      run: sudo apt-get update && sudo apt-get install -y nginx
      
    - name: Echo Sudeep
      run: echo "Sudeep!"
